### ISSUE TITLE
delete camera and feed icons in navigation and morph add goal into friend icon

### ISSUE THREAD

**Issue by carolw21** [FBX-2018-TeamTBD/goals#405]

**Comment by cassandrakane** [comment]
material io: https://material.io/design/components/buttons-floating-action-button.html#behavior
stackoverflow things:
https://stackoverflow.com/questions/31596640/fab-animation-with-viewpager-tabslider
https://stackoverflow.com/questions/31457099/android-fab-to-hide-when-navigating-between-different-fragments-in-a-viewpager?noredirect=1&lq=1
