### ISSUE TITLE
error with camera opening for new profile image

### ISSUE THREAD

**Issue by carolw21** [FBX-2018-TeamTBD/goals#56]
07-20 10:03:22.787 6649-6649/com.example.cassandrakane.goalz E/MessageQueue-JNI: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:content://com.fbu.fileprovider/images/Goals/null} (has extras) } from ProcessRecord{6ff91c7 6649:com.example.cassandrakane.goalz/u0a80} (pid=6649, uid=10080) with revoked permission android.permission.CAMERA

**Comment by carolw21** [comment]
I think it only happens for the first few times you use the camera

**Comment by carolw21** [comment]
Also error with selecting gallery image

**Comment by Demxr99** [comment]
Is this fixed now, since I set the permission?

**Comment by carolw21** [comment]
Yes.
